# blog configuration
keywords: 网络,安全,编程,开发,DIY,团队,管理,读书,Arduino,Python
author: repoog
description: 分享网络安全、软件开发和团队管理随笔.
avatar: /images/favicon.png
copyright: 2024

# contact information
contact:
  facebook: 
  twitter: https://twitter.com/repoog
  instagram: 
  github: https://github.com/repoog
  linkedin: 
  mail: mailto:repoog@gmail.com

# meta information below title
meta:
  # word count
  wordcount:
    enable: true
    # average word length: ZH≈2, EN≈5
    awl: 2
    # words per minute
    wpm: 60

# comment plugin
utterances:
  enable: true
  repo: repoog/repoog-blog
  label: Comment

